


slides:
	pdflatex -interaction=nonstopmode -shell-escape syllabus.tex

clean:
	rm -rf *.log *.aux *.toc *.log *.nav *.out *.snm *.pdf *.fdb_latex *.fls *.vrb _minted* *.data.minted *.fdb_latexmk ||:


