on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: install latex
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended

      - name: install requirements
        run: cd hardware-design && pip3 install -r requirements.txt

      - name: build
        run: cd hardware-design && make

      - name: Upload PDFs as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdfs
          path: "hardware-design/*/*.pdf"