on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: repo checkout
        uses: actions/checkout@v4

      - name: apt installs
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended python3 python3-pip python3-pygments

      - name: pip installs
        run: cd hardware-design && pip3 install -r requirements.txt

      - name: build
        run: cd hardware-design && make

      - name: uopload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-pdfs
          path: "hardware-design/*/*.pdf"